### ISSUE TITLE
constexpr only available in -std=c++11 or -std=gnu++11

### ISSUE THREAD

**Issue by dohmatob** [valentin-hartmann-research/semi-discrete-transport#1]
Hi,

I was trying out your code and hit the following problem (fixable).

Synopsis
=======
```
$ cmake . && make

[...]

semi-discrete-transport/opt_transport/measures/Source.h:80:5: error: ‘constexpr’ does not name a type
     constexpr static double EPS = 5e-2;
     ^
/home/elvis/Downloads/semi-discrete-transport/opt_transport/measures/Source.h:80:5: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/home/elvis/Downloads/semi-discrete-transport/opt_transport/measures/Source.cpp: In member function ‘int Source::progress(const lbfgsfloatval_t*, const lbfgsfloatval_t*, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, int, int, int)’:
/home/elvis/Downloads/semi-discrete-transport/opt_transport/measures/Source.cpp:160:26: error: ‘EPS’ was not declared in this scope
     if (mistransported < EPS) {
                          ^
```

Fix
===
- 1: Change `constexpr static double EPS = 5e-2;` to `const static double EPS = 5e-2;`, or
- 2: Add the following line in the CMakeLists.txt file

```
if(UNIX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=c++11")
endif()
```

I can quickly roll a PR to fix this, but wanna be sure we agree on this.

**Comment by valentin-hartmann-research** [comment]
I'm really sorry, I completely forgot about this. Thank you for your input!

With my current compiler version I don't experience this issue. Does it still occur on your machine? If yes, then I'd be grateful for a PR that fixes it for you. Fix 1 throws an error for me, but fix 2 seems to work.

**Comment by dschuhmacher** [comment]
I have the same issue with the current code when using the default compiler under MacOS (some old version of clang). Fix 2 works for me. Fix 1 also, but it seems this use of const is/was a GNU extension, so I'd vote for fix 2.

-Wall also gives a warning:

        semi-discrete-transport-master-5/opt_transport/measures/Target.cpp:42:5: warning: field 'grid' will be initialized after field 'masses' [-Wreorder]
        : grid(true), masses(masses) {
          ^

which seems self-explanatory (changing the order seems to fix it).
